In [80]:
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.ensemble import RandomForestClassifier as RFC
from sklearn.linear_model import LogisticRegression as LR
from sklearn.model_selection import train_test_split as TTS
from sklearn.preprocessing import StandardScaler as SS

import warnings 
warnings.filterwarnings('ignore')

In [81]:
#pulling in the dataset csv's 
df = pd.read_csv(Path('2019loans.csv'))

In [82]:
#looking at the training csv
df

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,pymnt_plan,dti,delinq_2yrs,inq_last_6mths,...,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag,target
0,7000.0,0.1894,256.38,MORTGAGE,75000.0,Not Verified,n,28.62,0.0,2.0,...,87.5,0.0,0.0,352260.0,62666.0,35000.0,10000.0,N,N,low_risk
1,40000.0,0.1614,975.71,MORTGAGE,102000.0,Source Verified,n,11.72,2.0,0.0,...,0.0,0.0,0.0,294664.0,109911.0,9000.0,71044.0,N,N,low_risk
2,11000.0,0.2055,294.81,RENT,45000.0,Verified,n,37.25,1.0,3.0,...,7.7,0.0,0.0,92228.0,36007.0,33000.0,46328.0,N,N,low_risk
3,4000.0,0.1612,140.87,MORTGAGE,38000.0,Not Verified,n,42.89,1.0,0.0,...,100.0,0.0,0.0,284273.0,52236.0,13500.0,52017.0,N,N,low_risk
4,14000.0,0.1797,505.93,MORTGAGE,43000.0,Source Verified,n,22.16,1.0,0.0,...,25.0,0.0,0.0,120280.0,88147.0,33300.0,78680.0,N,N,low_risk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12175,19975.0,0.2565,801.09,RENT,28000.0,Not Verified,n,28.42,0.0,0.0,...,16.7,0.0,0.0,50055.0,28192.0,18700.0,19055.0,N,N,high_risk
12176,15000.0,0.1774,540.34,RENT,50000.0,Verified,n,23.43,4.0,0.0,...,11.1,0.0,0.0,70324.0,57025.0,13300.0,54824.0,N,N,high_risk
12177,3600.0,0.1862,131.28,RENT,60000.0,Not Verified,n,28.80,0.0,1.0,...,0.0,0.0,0.0,83765.0,55156.0,14800.0,53065.0,N,N,high_risk
12178,15000.0,0.0881,475.68,MORTGAGE,62000.0,Source Verified,n,11.44,0.0,0.0,...,0.0,0.0,0.0,189930.0,23748.0,7000.0,32930.0,N,N,high_risk
12179,15000.0,0.1774,540.34,RENT,54080.0,Not Verified,n,21.66,1.0,1.0,...,100.0,0.0,0.0,48968.0,29786.0,2900.0,33968.0,N,N,high_risk

In [83]:
#setting y as target

y = pd.get_dummies(df['target'])
y = y['high_risk']
y

0        0
1        0
2        0
3        0
4        0
        ..
12175    1
12176    1
12177    1
12178    1
12179    1
Name: high_risk, Length: 12180, dtype: uint8

In [84]:
#for loop to change train_clean to_numeric

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = pd.to_numeric(df[col], errors='coerce')
        
df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,pymnt_plan,dti,delinq_2yrs,inq_last_6mths,...,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag,target
0,7000.0,0.1894,256.38,NaN,75000.0,NaN,NaN,28.62,0.0,2.0,...,87.5,0.0,0.0,352260.0,62666.0,35000.0,10000.0,NaN,NaN,NaN
1,40000.0,0.1614,975.71,NaN,102000.0,NaN,NaN,11.72,2.0,0.0,...,0.0,0.0,0.0,294664.0,109911.0,9000.0,71044.0,NaN,NaN,NaN
2,11000.0,0.2055,294.81,NaN,45000.0,NaN,NaN,37.25,1.0,3.0,...,7.7,0.0,0.0,92228.0,36007.0,33000.0,46328.0,NaN,NaN,NaN
3,4000.0,0.1612,140.87,NaN,38000.0,NaN,NaN,42.89,1.0,0.0,...,100.0,0.0,0.0,284273.0,52236.0,13500.0,52017.0,NaN,NaN,NaN
4,14000.0,0.1797,505.93,NaN,43000.0,NaN,NaN,22.16,1.0,0.0,...,25.0,0.0,0.0,120280.0,88147.0,33300.0,78680.0,NaN,NaN,NaN

In [85]:
#clean data by dropping all na's

df.dropna(axis='columns', how='all', inplace=True)

df

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,7000.0,0.1894,256.38,75000.0,28.62,0.0,2.0,20.0,0.0,40414.0,...,0.0,2.0,100.0,87.5,0.0,0.0,352260.0,62666.0,35000.0,10000.0
1,40000.0,0.1614,975.71,102000.0,11.72,2.0,0.0,10.0,0.0,43531.0,...,0.0,0.0,85.7,0.0,0.0,0.0,294664.0,109911.0,9000.0,71044.0
2,11000.0,0.2055,294.81,45000.0,37.25,1.0,3.0,23.0,0.0,8242.0,...,0.0,6.0,94.3,7.7,0.0,0.0,92228.0,36007.0,33000.0,46328.0
3,4000.0,0.1612,140.87,38000.0,42.89,1.0,0.0,7.0,0.0,12767.0,...,0.0,0.0,92.9,100.0,0.0,0.0,284273.0,52236.0,13500.0,52017.0
4,14000.0,0.1797,505.93,43000.0,22.16,1.0,0.0,22.0,0.0,11182.0,...,1.0,3.0,84.1,25.0,0.0,0.0,120280.0,88147.0,33300.0,78680.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12175,19975.0,0.2565,801.09,28000.0,28.42,0.0,0.0,15.0,0.0,9679.0,...,0.0,3.0,100.0,16.7,0.0,0.0,50055.0,28192.0,18700.0,19055.0
12176,15000.0,0.1774,540.34,50000.0,23.43,4.0,0.0,16.0,0.0,3193.0,...,2.0,2.0,90.5,11.1,0.0,0.0,70324.0,57025.0,13300.0,54824.0
12177,3600.0,0.1862,131.28,60000.0,28.80,0.0,1.0,14.0,0.0,11804.0,...,0.0,5.0,100.0,0.0,0.0,0.0,83765.0,55156.0,14800.0,53065.0
12178,15000.0,0.0881,475.68,62000.0,11.44,0.0,0.0,5.0,0.0,157.0,...,0.0,1.0,100.0,0.0,0.0,0.0,189930.0,23748.0,7000.0,32930.0
12179,15000.0,0.1774,540.34,54080.0,21.66,1.0,1.0,5.0,0.0,8349.0,...,0.0,1.0,90.0,100.0,0.0,0.0,48968.0,29786.0,2900.0,33968.0

In [86]:
#creating x
x = df

In [87]:
#creating training and testing sets

xtrain, xtest, ytrain, ytest = TTS(x,y,random_state=1)

In [ ]:
# my assumptions:
# Logistic Regression without Scaled Data will be the least accurate
# Random Forest Classifier without Scaled Data will be more accurate

#My reasoning behind this is because a random sampling of data is usually better than a larger sampling of a non-random data set
#the only thing that could throw this off is that the Logistic Regression may be able to capture all of the data that we are 
#sampling in this instance.

In [88]:
# Train the Logistic Regression model on the unscaled data and print the model score
classifier = LR()
classifier.fit(xtrain, ytrain)

print(f'Training Data Score: {classifier.score(xtrain, ytrain)}')
print(f'Testing Data Score: {classifier.score(xtest, ytest)}')

Training Data Score: 0.6500273672687465
Testing Data Score: 0.6512315270935961

In [89]:
# Train a Random Forest Classifier model and print the model score
clf = RFC(random_state = 1, n_estimators=500).fit(xtrain, ytrain)
print(f'Training Data Score: {clf.score(xtrain, ytrain)}')
print(f'Testing Data Score: {clf.score(xtest, ytest)}')

Training Data Score: 1.0
Testing Data Score: 0.7878489326765189

In [90]:
# Scale the data

scale = SS().fit(xtrain)
xtrain_scaled = scale.transform(xtrain)
xtest_scaled = scale.transform(xtest)

In [ ]:
# my assumptions:
# Logistic Regression with Scaled Data will be the least accurate of this data set (but more accurate the the data set above)
# Random Forest Classifier with Scaled Data will be the most accurate of all the data sets

#My reasoning goes back to the idea of a random sampling of data vs more data that is not random. My assumptions on this data
#set is one that is assuming that the scaled data will produce a more accurate data set overall.

In [91]:
# Train the Logistic Regression model on the scaled data and print the model score
classifier = LR()
classifier.fit(xtrain_scaled, ytrain)

print(f'Training Data Score: {classifier.score(xtrain_scaled, ytrain)}')
print(f'Testing Data Score: {classifier.score(xtest_scaled, ytest)}')

Training Data Score: 0.7062944718117132
Testing Data Score: 0.7205254515599343

In [92]:
# Train a Random Forest Classifier model on the scaled data and print the model score

clf = RFC(random_state = 1, n_estimators=500).fit(xtrain_scaled, ytrain)
print(f'Training Data Score: {clf.score(xtrain_scaled, ytrain)}')
print(f'Testing Data Score: {clf.score(xtest_scaled, ytest)}')

Training Data Score: 1.0
Testing Data Score: 0.7875205254515599